// https://{{api_key}}:{{api_secret}}@api.{{cluster}}.com/{{lang}}/orders/{order_id}.json
// ----------------------------------------------------------------------

export const order_detail = {
  order: {
    id: 218248201,
    createdAt: '2022-06-14T14:24:34+02:00',
    updatedAt: '2022-06-17T22:56:38+02:00',
    number: 'ORD00003',
    status: 'cancelled',
    customStatusId: null,
    channel: '',
    remoteIp: '35.204.91.65',
    userAgent: 'WebshopappApi',
    referralId: false,
    priceCost: 103.92,
    priceExcl: 219.64,
    priceIncl: 265.77,
    weight: 0,
    volume: 0,
    colli: 0,
    gender: 'male',
    birthDate: false,
    nationalId: '',
    email: 'matser@onlinedistributeur.nl',
    firstname: 'Test',
    middlename: 'de',
    lastname: 'Tester',
    phone: '+0642742626',
    mobile: '',
    newsletterSubscribed: false,
    isCompany: false,
    companyName: '',
    companyCoCNumber: '',
    companyVatNumber: '',
    addressBillingName: 'Test de Tester',
    addressBillingStreet: 'Meester Treublaan',
    addressBillingStreet2: '',
    addressBillingNumber: '3',
    addressBillingExtension: '',
    addressBillingZipcode: '1097DP',
    addressBillingCity: 'Amsterdam',
    addressBillingRegion: 'Noord-Holland',
    addressBillingCountry: {
      id: 150,
      code: 'nl',
      code3: 'nld',
      title: 'Netherlands, The',
    },
    addressBillingRegionData: {
      id: 5736,
      name: 'Noord-Holland',
      code: 'NH',
    },
    addressShippingCompany: false,
    addressShippingName: 'Test de Tester',
    addressShippingStreet: 'Meester Treublaan',
    addressShippingStreet2: '',
    addressShippingNumber: '3',
    addressShippingExtension: '',
    addressShippingZipcode: '1097DP',
    addressShippingCity: 'Amsterdam',
    addressShippingRegion: 'Noord-Holland',
    addressShippingCountry: {
      id: 150,
      code: 'nl',
      code3: 'nld',
      title: 'Netherlands, The',
    },
    addressShippingRegionData: {
      id: 5736,
      name: 'Noord-Holland',
      code: 'NH',
    },
    paymentId: 'external',
    paymentStatus: 'cancelled',
    paymentIsPost: false,
    paymentIsInvoiceExternal: false,
    paymentTaxRate: 0,
    paymentTaxRates: [
      {
        name: 'VAT',
        rate: 0,
        amount: 0,
      },
    ],
    paymentBasePriceExcl: 0,
    paymentBasePriceIncl: 0,
    paymentPriceExcl: 0,
    paymentPriceIncl: 0,
    paymentTitle: 'Customer choice',
    paymentData: {
      user_id: null,
    },
    shipmentId: 'core|688006|2566484',
    shipmentStatus: 'cancelled',
    shipmentIsCashOnDelivery: false,
    shipmentIsPickup: false,
    shipmentTaxRate: 0.21,
    shipmentTaxRates: [
      {
        name: 'VAT',
        rate: 0.21,
        amount: 1.0332,
      },
    ],
    shipmentBasePriceExcl: 4.9174,
    shipmentBasePriceIncl: 5.95,
    shipmentPriceExcl: 4.92,
    shipmentPriceIncl: 5.95,
    shipmentDiscountExcl: 0,
    shipmentDiscountIncl: 0,
    shipmentTitle: 'Standaart verzending',
    shipmentData: {
      method: 'default',
      shipment_id: 688006,
      shipping_value_id: 2566484,
    },
    shippingDate: null,
    deliveryDate: null,
    isDiscounted: false,
    discountType: 'amount',
    discountAmount: 0,
    discountPercentage: 0,
    discountCouponCode: '',
    taxRates: [
      {
        name: 'VAT',
        rate: 0.21,
        amount: 45.0912,
      },
    ],
    isNewCustomer: false,
    comment: '',
    memo: 'Memo',
    allowNotifications: true,
    doNotifyNew: false,
    doNotifyReminder: false,
    doNotifyCancelled: false,
    language: {
      id: 1,
      code: 'nl',
      locale: 'nl_NL',
      title: 'Nederlands',
    },
    customer: {
      resource: {
        id: 160885439,
        url: 'customers/160885439',
        link: 'https://api.webshopapp.com/nl/customers/160885439.json',
        embedded: {
          id: 160885439,
          createdAt: '2022-06-14T14:22:20+02:00',
          updatedAt: '2022-06-14T14:25:34+02:00',
          isConfirmed: false,
          type: 'registered',
          lastOnlineAt: '2022-06-14T14:24:34+02:00',
          remoteIp: '35.204.91.65',
          userAgent: 'WebshopappApi',
          referralId: false,
          gender: 'male',
          birthDate: false,
          nationalId: '',
          email: 'matser@onlinedistributeur.nl',
          firstname: 'Test',
          middlename: 'de',
          lastname: 'Tester',
          phone: '+0642742626',
          mobile: '',
          isCompany: false,
          companyName: '',
          companyCoCNumber: '',
          companyVatNumber: '',
          addressBillingName: 'Test de Tester',
          addressBillingStreet: 'Meester Treublaan',
          addressBillingStreet2: '',
          addressBillingNumber: '3',
          addressBillingExtension: '',
          addressBillingZipcode: '1097DP',
          addressBillingCity: 'Amsterdam',
          addressBillingRegion: 'Noord-Holland',
          addressBillingCountry: {
            id: 150,
            code: 'nl',
            code3: 'nld',
            title: 'Netherlands, The',
          },
          addressShippingCompany: false,
          addressShippingName: 'Test de Tester',
          addressShippingStreet: 'Meester Treublaan',
          addressShippingStreet2: '',
          addressShippingNumber: '3',
          addressShippingExtension: '',
          addressShippingZipcode: '1097DP',
          addressShippingCity: 'Amsterdam',
          addressShippingRegion: 'Noord-Holland',
          addressShippingCountry: {
            id: 150,
            code: 'nl',
            code3: 'nld',
            title: 'Netherlands, The',
          },
          memo: null,
          doNotifyRegistered: false,
          doNotifyConfirmed: false,
          doNotifyPassword: false,
          groups: {
            resource: {
              id: false,
              url: 'groups/customers?customer=160885439',
              link: 'https://api.webshopapp.com/nl/groups/customers.json?customer=160885439',
            },
          },
          invoices: {
            resource: {
              id: false,
              url: 'invoices?customer=160885439',
              link: 'https://api.webshopapp.com/nl/invoices.json?customer=160885439',
            },
          },
          language: {
            id: 1,
            code: 'nl',
            locale: 'nl_NL',
            title: 'Nederlands',
          },
          orders: {
            resource: {
              id: false,
              url: 'orders?customer=160885439',
              link: 'https://api.webshopapp.com/nl/orders.json?customer=160885439',
            },
          },
          reviews: {
            resource: {
              id: false,
              url: 'reviews?customer=160885439',
              link: 'https://api.webshopapp.com/nl/reviews.json?customer=160885439',
            },
          },
          shipments: {
            resource: {
              id: false,
              url: 'shipments?customer=160885439',
              link: 'https://api.webshopapp.com/nl/shipments.json?customer=160885439',
            },
          },
          tickets: {
            resource: {
              id: false,
              url: 'tickets?customer=160885439',
              link: 'https://api.webshopapp.com/nl/tickets.json?customer=160885439',
            },
          },
          metafields: {
            resource: {
              id: false,
              url: 'customers/160885439/metafields',
              link: 'https://api.webshopapp.com/nl/customers/160885439/metafields.json',
            },
          },
          login: {
            resource: {
              id: false,
              url: 'customers/160885439/login',
              link: 'https://api.webshopapp.com/nl/customers/160885439/login.json',
            },
          },
        },
      },
    },
    invoices: {
      resource: {
        id: false,
        url: 'invoices?order=218248201',
        link: 'https://api.webshopapp.com/nl/invoices.json?order=218248201',
        embedded: [
          {
            id: 230195057,
            createdAt: '2022-06-14T14:24:34+02:00',
            updatedAt: '2022-06-14T14:24:38+02:00',
            number: 'INV00004',
            status: 'paid',
            isVatShifted: false,
            priceExcl: 219.64,
            priceIncl: 265.77,
            doNotifyNew: false,
            doNotifyPaid: false,
            invoice: false,
            isCreditNote: false,
            creditNote: {
              resource: {
                id: 230512048,
                url: 'invoices/230512048',
                link: 'https://api.webshopapp.com/nl/invoices/230512048.json',
              },
            },
            order: {
              resource: {
                id: 218248201,
                url: 'orders/218248201',
                link: 'https://api.webshopapp.com/nl/orders/218248201.json',
              },
            },
            customer: {
              resource: {
                id: 160885439,
                url: 'customers/160885439',
                link: 'https://api.webshopapp.com/nl/customers/160885439.json',
              },
            },
            items: {
              resource: {
                id: false,
                url: 'invoices/230195057/items',
                link: 'https://api.webshopapp.com/nl/invoices/230195057/items.json',
              },
            },
            metafields: {
              resource: {
                id: false,
                url: 'invoices/230195057/metafields',
                link: 'https://api.webshopapp.com/nl/invoices/230195057/metafields.json',
              },
            },
            events: {
              resource: {
                id: false,
                url: 'orders/events?invoice=230195057',
                link: 'https://api.webshopapp.com/nl/orders/events.json?invoice=230195057',
              },
            },
          },
          {
            id: 230512048,
            createdAt: '2022-06-17T22:56:33+02:00',
            updatedAt: '2022-06-17T22:56:33+02:00',
            number: 'INV00005',
            status: 'not_paid',
            isVatShifted: false,
            priceExcl: -219.64,
            priceIncl: -265.77,
            doNotifyNew: false,
            doNotifyPaid: false,
            invoice: {
              resource: {
                id: 230195057,
                url: 'invoices/230195057',
                link: 'https://api.webshopapp.com/nl/invoices/230195057.json',
              },
            },
            isCreditNote: true,
            creditNote: false,
            order: {
              resource: {
                id: 218248201,
                url: 'orders/218248201',
                link: 'https://api.webshopapp.com/nl/orders/218248201.json',
              },
            },
            customer: {
              resource: {
                id: 160885439,
                url: 'customers/160885439',
                link: 'https://api.webshopapp.com/nl/customers/160885439.json',
              },
            },
            items: {
              resource: {
                id: false,
                url: 'invoices/230512048/items',
                link: 'https://api.webshopapp.com/nl/invoices/230512048/items.json',
              },
            },
            metafields: {
              resource: {
                id: false,
                url: 'invoices/230512048/metafields',
                link: 'https://api.webshopapp.com/nl/invoices/230512048/metafields.json',
              },
            },
            events: {
              resource: {
                id: false,
                url: 'orders/events?invoice=230512048',
                link: 'https://api.webshopapp.com/nl/orders/events.json?invoice=230512048',
              },
            },
          },
        ],
      },
    },
    shipments: {
      resource: {
        id: false,
        url: 'shipments?order=218248201',
        link: 'https://api.webshopapp.com/nl/shipments.json?order=218248201',
        embedded: [
          {
            id: 211143244,
            createdAt: '2022-06-14T14:24:34+02:00',
            updatedAt: '2022-06-17T22:56:33+02:00',
            number: 'SHIP00003',
            status: 'cancelled',
            trackingCode: '',
            doNotifyShipped: false,
            doNotifyReadyForPickup: false,
            doNotifyTrackingCode: false,
            customer: {
              resource: {
                id: 160885439,
                url: 'customers/160885439',
                link: 'https://api.webshopapp.com/nl/customers/160885439.json',
              },
            },
            order: {
              resource: {
                id: 218248201,
                url: 'orders/218248201',
                link: 'https://api.webshopapp.com/nl/orders/218248201.json',
              },
            },
            products: {
              resource: {
                id: false,
                url: 'shipments/211143244/products',
                link: 'https://api.webshopapp.com/nl/shipments/211143244/products.json',
              },
            },
            metafields: {
              resource: {
                id: false,
                url: 'shipments/211143244/metafields',
                link: 'https://api.webshopapp.com/nl/shipments/211143244/metafields.json',
              },
            },
            events: {
              resource: {
                id: false,
                url: 'orders/events?shipment=211143244',
                link: 'https://api.webshopapp.com/nl/orders/events.json?shipment=211143244',
              },
            },
          },
        ],
      },
    },
    products: {
      resource: {
        id: false,
        url: 'orders/218248201/products',
        link: 'https://api.webshopapp.com/nl/orders/218248201/products.json',
        embedded: [
          {
            id: 434714393,
            supplierTitle: '',
            brandTitle: 'Cawö',
            productTitle: 'Cawo Badjas 2359 Velours met Sjaalkraag',
            variantTitle: '"Color: Marine","Size: 48"',
            taxRate: 0.21,
            taxRates: [
              {
                name: 'VAT',
                rate: 0.21,
                amount: 22.5456,
              },
            ],
            quantityOrdered: 1,
            quantityInvoiced: 1,
            quantityShipped: 0,
            quantityRefunded: 0,
            quantityReturned: 1,
            articleCode: '',
            ean: '4011638960198',
            sku: '2359-171-48',
            weight: 0,
            volume: 0,
            colli: 0,
            sizeX: 0,
            sizeY: 0,
            sizeZ: 0,
            priceCost: 51.96,
            customExcl: 0,
            customIncl: 0,
            basePriceExcl: 107.3636,
            basePriceIncl: 129.91,
            priceExcl: 107.36,
            priceIncl: 129.91,
            discountExcl: 0,
            discountIncl: 0,
            customFields: false,
            product: {
              resource: {
                id: 126342132,
                url: 'products/126342132',
                link: 'https://api.webshopapp.com/nl/products/126342132.json',
              },
            },
            variant: {
              resource: {
                id: 251496793,
                url: 'variants/251496793',
                link: 'https://api.webshopapp.com/nl/variants/251496793.json',
              },
            },
          },
          {
            id: 434714394,
            supplierTitle: '',
            brandTitle: 'Cawö',
            productTitle: 'Cawo Badjas 2359 Velours met Sjaalkraag',
            variantTitle: '"Color: Marine","Size: 52"',
            taxRate: 0.21,
            taxRates: [
              {
                name: 'VAT',
                rate: 0.21,
                amount: 22.5456,
              },
            ],
            quantityOrdered: 1,
            quantityInvoiced: 1,
            quantityShipped: 0,
            quantityRefunded: 0,
            quantityReturned: 1,
            articleCode: '',
            ean: '4011638960211',
            sku: '',
            weight: 0,
            volume: 0,
            colli: 0,
            sizeX: 0,
            sizeY: 0,
            sizeZ: 0,
            priceCost: 51.96,
            customExcl: 0,
            customIncl: 0,
            basePriceExcl: 107.3636,
            basePriceIncl: 129.91,
            priceExcl: 107.36,
            priceIncl: 129.91,
            discountExcl: 0,
            discountIncl: 0,
            customFields: false,
            product: {
              resource: {
                id: 126342132,
                url: 'products/126342132',
                link: 'https://api.webshopapp.com/nl/products/126342132.json',
              },
            },
            variant: {
              resource: {
                id: 251496791,
                url: 'variants/251496791',
                link: 'https://api.webshopapp.com/nl/variants/251496791.json',
              },
            },
          },
        ],
      },
    },
    metafields: {
      resource: {
        id: false,
        url: 'orders/218248201/metafields',
        link: 'https://api.webshopapp.com/nl/orders/218248201/metafields.json',
        embedded: [],
      },
    },
    quote: {
      resource: {
        id: 925154209,
        url: 'quotes/925154209',
        link: 'https://api.webshopapp.com/nl/quotes/925154209.json',
        embedded: {
          id: 925154209,
          createdAt: '2022-06-14T14:24:28+02:00',
          updatedAt: '2022-06-14T14:24:34+02:00',
          recalculatedAt: '2022-06-14T14:24:34+02:00',
          isLocked: false,
          channel: 'backend',
          recoveryHash: '6ed42a8dd239ea320611aaa925154209',
          remoteIp: '35.204.91.65',
          userAgent: 'WebshopappApi',
          referralId: false,
          weight: 0,
          volume: 0,
          colli: 0,
          paymentCountry: {
            id: 150,
            code: 'nl',
            code3: 'nld',
            title: 'Netherlands, The',
          },
          shipmentCountry: {
            id: 150,
            code: 'nl',
            code3: 'nld',
            title: 'Netherlands, The',
          },
          shipmentZipcode: '1097DP',
          shipmentSameAddress: true,
          priceCost: 103.92,
          priceExcl: 219.64,
          priceIncl: 265.77,
          discountExcl: 0,
          discountIncl: 0,
          productsCount: 2,
          productsQuantity: 2,
          shipmentIsSet: true,
          shipmentId: 'core|688006|2566484',
          shipmentIsVirtual: false,
          shipmentIsCashOnDelivery: false,
          shipmentDiscountPercentage: 0,
          shipmentIsServicePoint: false,
          shipmentIsPickup: false,
          shipmentTaxRate: 0.21,
          shipmentBasePriceExcl: 4.9174,
          shipmentBasePriceIncl: 5.95,
          shipmentPriceTax: 1.03,
          shipmentPriceExcl: 4.92,
          shipmentPriceIncl: 5.95,
          shipmentDiscountExcl: 0,
          shipmentDiscountIncl: 0,
          shipmentTitle: 'Standaart verzending',
          shipmentData: {
            method: 'default',
            shipment_id: 688006,
            shipping_value_id: 2566484,
          },
          paymentIsSet: true,
          paymentId: 'external',
          paymentIsPost: false,
          paymentIsInvoiceExternal: false,
          paymentData: '{"user_id":null}',
          paymentTaxRate: 0,
          paymentBasePriceExcl: 0,
          paymentBasePriceIncl: 0,
          paymentPriceTax: 0,
          paymentPriceExcl: 0,
          paymentPriceIncl: 0,
          additionalCostIncl: '0.0000',
          additionalCostExcl: '0.0000',
          paymentTitle: 'Customer choice',
          discountIsSet: false,
          discountId: 0,
          discountType: 'amount',
          discountAmount: 0,
          discountPercentage: 0,
          discountShipment: 'default',
          discountMinimumAmount: '0.00',
          discountCouponCode: '',
          comment: null,
          allowNotifications: true,
          customer: {
            resource: {
              id: 160885439,
              url: 'customers/160885439',
              link: 'https://api.webshopapp.com/nl/customers/160885439.json',
            },
          },
          language: {
            id: 1,
            code: 'nl',
            locale: 'nl_NL',
            title: 'Nederlands',
          },
          products: {
            resource: {
              id: false,
              url: 'quotes/925154209/products',
              link: 'https://api.webshopapp.com/nl/quotes/925154209/products.json',
            },
          },
          shippingmethods: {
            resource: {
              id: false,
              url: 'quotes/925154209/shippingmethods',
              link: 'https://api.webshopapp.com/nl/quotes/925154209/shippingmethods.json',
            },
          },
          paymentmethods: {
            resource: {
              id: false,
              url: 'quotes/925154209/paymentmethods',
              link: 'https://api.webshopapp.com/nl/quotes/925154209/paymentmethods.json',
            },
          },
        },
      },
    },
    events: {
      resource: {
        id: false,
        url: 'orders/events?order=218248201',
        link: 'https://api.webshopapp.com/nl/orders/events.json?order=218248201',
        embedded: [
          {
            id: 2158244507,
            createdAt: '2022-06-14T14:24:34+02:00',
            channel: 'manual',
            type: 'order',
            message: 'new',
            comment: null,
            order: {
              resource: {
                id: 218248201,
                url: 'orders/218248201',
                link: 'https://api.webshopapp.com/nl/orders/218248201.json',
              },
            },
            invoice: false,
            shipment: false,
          },
          {
            id: 2158244508,
            createdAt: '2022-06-14T14:24:34+02:00',
            channel: 'auto',
            type: 'invoice',
            message: 'new',
            comment: null,
            order: {
              resource: {
                id: 218248201,
                url: 'orders/218248201',
                link: 'https://api.webshopapp.com/nl/orders/218248201.json',
              },
            },
            invoice: {
              resource: {
                id: 230195057,
                url: 'invoices/230195057',
                link: 'https://api.webshopapp.com/nl/invoices/230195057.json',
              },
            },
            shipment: false,
          },
          {
            id: 2158244509,
            createdAt: '2022-06-14T14:24:34+02:00',
            channel: 'auto',
            type: 'shipment',
            message: 'new',
            comment: null,
            order: {
              resource: {
                id: 218248201,
                url: 'orders/218248201',
                link: 'https://api.webshopapp.com/nl/orders/218248201.json',
              },
            },
            invoice: false,
            shipment: {
              resource: {
                id: 211143244,
                url: 'shipments/211143244',
                link: 'https://api.webshopapp.com/nl/shipments/211143244.json',
              },
            },
          },
          {
            id: 2158244545,
            createdAt: '2022-06-14T14:24:36+02:00',
            channel: 'auto',
            type: 'notification',
            message: 'new',
            comment: null,
            order: {
              resource: {
                id: 218248201,
                url: 'orders/218248201',
                link: 'https://api.webshopapp.com/nl/orders/218248201.json',
              },
            },
            invoice: false,
            shipment: false,
          },
          {
            id: 2158244568,
            createdAt: '2022-06-14T14:24:37+02:00',
            channel: 'manual',
            type: 'order',
            message: 'paid',
            comment: null,
            order: {
              resource: {
                id: 218248201,
                url: 'orders/218248201',
                link: 'https://api.webshopapp.com/nl/orders/218248201.json',
              },
            },
            invoice: false,
            shipment: false,
          },
          {
            id: 2158244570,
            createdAt: '2022-06-14T14:24:37+02:00',
            channel: 'manual',
            type: 'notification',
            message: 'paid',
            comment: null,
            order: {
              resource: {
                id: 218248201,
                url: 'orders/218248201',
                link: 'https://api.webshopapp.com/nl/orders/218248201.json',
              },
            },
            invoice: false,
            shipment: false,
          },
          {
            id: 2158244609,
            createdAt: '2022-06-14T14:24:39+02:00',
            channel: 'auto',
            type: 'notification',
            message: 'paid',
            comment: null,
            order: {
              resource: {
                id: 218248201,
                url: 'orders/218248201',
                link: 'https://api.webshopapp.com/nl/orders/218248201.json',
              },
            },
            invoice: {
              resource: {
                id: 230195057,
                url: 'invoices/230195057',
                link: 'https://api.webshopapp.com/nl/invoices/230195057.json',
              },
            },
            shipment: false,
          },
          {
            id: 2161137883,
            createdAt: '2022-06-17T22:56:33+02:00',
            channel: 'api',
            type: 'invoice',
            message: 'not_paid',
            comment: null,
            order: {
              resource: {
                id: 218248201,
                url: 'orders/218248201',
                link: 'https://api.webshopapp.com/nl/orders/218248201.json',
              },
            },
            invoice: false,
            shipment: false,
          },
          {
            id: 2161137884,
            createdAt: '2022-06-17T22:56:33+02:00',
            channel: 'api',
            type: 'invoice',
            message: 'new',
            comment: null,
            order: {
              resource: {
                id: 218248201,
                url: 'orders/218248201',
                link: 'https://api.webshopapp.com/nl/orders/218248201.json',
              },
            },
            invoice: {
              resource: {
                id: 230512048,
                url: 'invoices/230512048',
                link: 'https://api.webshopapp.com/nl/invoices/230512048.json',
              },
            },
            shipment: false,
          },
          {
            id: 2161137885,
            createdAt: '2022-06-17T22:56:33+02:00',
            channel: 'api',
            type: 'shipment',
            message: 'cancelled',
            comment: null,
            order: {
              resource: {
                id: 218248201,
                url: 'orders/218248201',
                link: 'https://api.webshopapp.com/nl/orders/218248201.json',
              },
            },
            invoice: false,
            shipment: {
              resource: {
                id: 211143244,
                url: 'shipments/211143244',
                link: 'https://api.webshopapp.com/nl/shipments/211143244.json',
              },
            },
          },
          {
            id: 2161137886,
            createdAt: '2022-06-17T22:56:33+02:00',
            channel: 'api',
            type: 'order',
            message: 'cancelled',
            comment: null,
            order: {
              resource: {
                id: 218248201,
                url: 'orders/218248201',
                link: 'https://api.webshopapp.com/nl/orders/218248201.json',
              },
            },
            invoice: false,
            shipment: false,
          },
        ],
      },
    },
    giftCardsPayment: [],
  },
};
